### ISSUE TITLE
Download always stops before it reaches the limit

### ISSUE THREAD

**Issue by imageschool** [tomahim/py-image-dataset-generator#10]
Thank you very much for your generator :-] This is indeed helpful!
Not sure if this is just for me but it always stops before it runs fully!

![image](https://user-images.githubusercontent.com/29969006/37696762-bf855c90-2cd0-11e8-8cb0-6c26887df8a8.png)

Also, is this okay to run it on multiple command line ?

**Comment by tomahim** [comment]
Hi,

First you may need to increase manually in this file the number of scroll selenium is doing : 

https://github.com/tomahim/py-image-dataset-generator/blob/81f47ccb8dd5c5f7fa58bcaa5081b1f31399aeda/image_grabber/google_grabber.py#L39

For now it's set to 20 scrolls but you can increase to let's say 100 or 200, it should be enought if you want to download let's say 1000 images. I planed to improve this to automatically adapt the number of scrolls depending on the limit of download desired (if you want to contribute feel free !)

Sometimes the script may fail to download some images (401, 403 or 500 happens...), so for now you will not have exactly the number requested. But increasing the number above may resolve this also 

Thank you for your feedback !

**Comment by tomahim** [comment]
For your second question you can run it on multiple command line but if you request the same keyword "cat" it will download the same images from the start of the Google search page. So it's very useful.

**Comment by imageschool** [comment]
Thank you very much for your quick reply, I will try when I get home and close the issue!

**Comment by imageschool** [comment]
I have changed the variable value to 150, however it seems like it is not changing much hehe :-(

![image](https://user-images.githubusercontent.com/29969006/37747938-7c7cc2f4-2d79-11e8-8a24-1439ce74fb66.png)

![image](https://user-images.githubusercontent.com/29969006/37747988-bcba6a56-2d79-11e8-8135-7ec61ef34d5d.png)

**Comment by tomahim** [comment]
Ok I think something else is wrong. I will investigate as soon as I can.

**Comment by imageschool** [comment]
@tomahim by the way, can I ask you one thing regarding training neural network in general ?

**Comment by tomahim** [comment]
I would be happy to chat on the gitter of this  repo if I could help you in some way https://gitter.im/py-image-dataset-generator/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by tomahim** [comment]
Hi there,

I just made a [fix](https://github.com/tomahim/py-image-dataset-generator/commit/84be26412633380590a30f69d6c0917dc64a4801). I noticed some issues too, Google and Bing won't let you display more than 700 or 900 images on the same page. But if you want more than 700 images, you can use the `-allsources` parameters, which will grab images from Google and Bing at the same time, so you will be able to have more than a thousand images in one command line.

For instance, I managed to have 1000 images of 'popular meme' with this command

`python download.py "popular meme" -limit=100 -resize=250x250 -allsources`

I home it helps !

**Comment by imageschool** [comment]
Thank you very much, it helped me a lot!
I completely forgot about this thread X)

**Comment by tuannguyenngoc** [comment]
Hi there,
Thank you very much for your project. It's very helpful.
I have the same problem when it stops downloading before reaching limit.
![capture](https://user-images.githubusercontent.com/38061474/41004013-c6118814-695b-11e8-925f-8e8f8636cb09.JPG)
I notice that it only finds 710 images on both Google and Bing which is unusual because I think there are more "popular meme" on two sites. And you mentioned you were able to download 1000 images.
In bing_grabber.py and google_grabber.py, I tried to increase no_of_pages_down to 200/300 (no_of_pages_down = 20 if nb_images < 300 else 200) but it did not help.
My system:
OS: Windows 7 Enterprise
Chrome: Version 67.0.3396.62 (Official Build) (64-bit)
Anaconda 5.2.0 Python 6.4.0
Can you please help?
Thank you.
